### ISSUE TITLE
realmid returned from querystring is larger than int datatype of OAuthTokens realmid

### ISSUE THREAD

**Issue by varikhehra** [IntuitDeveloper/SampleApp-TimeTracking_Invoicing-DotNet#3]
Error at following line in OauthController.cs file
realmid value in querystring is too large for int datatype....needs to change it to large datatype

oAuthorizationDB.realmid = Convert.ToInt32(Request.QueryString["realmId"].ToString());

**Comment by nimisha84** [comment]
Yes, it is a bug in the sample app. Please convert realmId to string everywhere.

**Comment by varikhehra** [comment]
Thank you Nimisha! Not sure if you could upload a working sample app?

**Comment by varikhehra** [comment]
Tried changing DB realmid field to string and now getting following error.

![error](https://cloud.githubusercontent.com/assets/6885749/15942877/64e33392-2e54-11e6-97aa-e049bd94f805.jpg)

**Comment by nimisha84** [comment]
I can ask the SDK team to fix it but it will take sometime.
You will have to fix the type of RealmId everywhere to fix this issue.
Model, Controller etc..
If you cannot do that right away, I would suggest you to use another web forms sample app or the .Net MVC3 sample we have.

Web forms-
https://github.com/IntuitDeveloperRelations/QuickbooksV3API-DotNet

MVC3-
https://github.com/IntuitDeveloper/QuickbooksV3API-DotNet-Mvc3-Sample

**Comment by smathilakath** [comment]
I guess you can solve this problem using a BIG INTEGER because a decimal works differently to float and double - it always has enough information to store as far as integer precision, as the maximum exponent is 28 and it has 28-29 digits of precision decimal works differently to float and double - it always has enough information to store as far as integer precision, as the maximum exponent is 28 and it has 28-29 digits of precision

So you can store any integer in the range [decimal.MinValue, decimal.MaxValue] without losing any precision.If you want a wider range than that, you should use BigInteger.

Ref : https://msdn.microsoft.com/en-us/library/system.numerics.biginteger.aspx

Solution : 
-- Navigate to class OAuthorizationdto
-- Search for property public int Realmid { get; set; } 
-- Change type to BIG INT

Hope this helps!

Thanks,
Sumod Madhavan

**Comment by varikhehra** [comment]
Sumod Thank you for your response!

I have changed Realmid to BIGINT in DB and long in code everywhere but still getting following screen shot error. 

![error](https://cloud.githubusercontent.com/assets/6885749/15946043/01f37d14-2e63-11e6-9c50-adf4eefcf810.jpg)

**Comment by varikhehra** [comment]
Hey Nimisha:

I tried following example samples sent by you but none of those is working as well.

Web forms-
https://github.com/IntuitDeveloperRelations/QuickbooksV3API-DotNet
![quickbooksv3api-dotnet](https://cloud.githubusercontent.com/assets/6885749/15946204/c1fe947c-2e63-11e6-888f-3dd5670b721d.jpg)


MVC3-
https://github.com/IntuitDeveloper/QuickbooksV3API-DotNet-Mvc3-Sample
![quickbooksv3api-dotnet-mvc3-sample](https://cloud.githubusercontent.com/assets/6885749/15946268/186f7010-2e64-11e6-8823-38f706faa91e.jpg)

**Comment by smathilakath** [comment]
- As you have modified the type it resulted in schema change of entity framework. 
-- You can update the schema to accept new changes.
Ref :
![image](https://cloud.githubusercontent.com/assets/9986042/15946224/7c655888-2eb3-11e6-90ca-645187c4fbed.png)

Thanks,
Sumod Madhavan

**Comment by nimisha84** [comment]
Please post your queries on https://intuitdeveloper.lc.intuit.com/questions.

**Comment by varikhehra** [comment]
I have updated EF class and DB also but no luck...same error.
![error](https://cloud.githubusercontent.com/assets/6885749/15946909/e8549196-2e66-11e6-9b1b-1842cb42d704.jpg)

**Comment by smathilakath** [comment]
Ok cool. You can try few things to keep moving else you can wait for the doctor. :)

-- You can disable the migration part of the dbcontext.
-- You can update or fix the schema.
--For example : Refer here
![image](https://cloud.githubusercontent.com/assets/9986042/15985992/fb37043c-301a-11e6-8c95-a4926f0b53af.png)

-- You can also refer here to disable.
http://stackoverflow.com/questions/3600175/the-model-backing-the-database-context-has-changed-since-the-database-was-crea

-- I would personally recommend changing the type from Int to BIG INT over string or character is because with an integer, there exist instructions on the machine level which can perform a comparison in one cycle which bring down your time and space complexity to O(n) during comparisons to multiple realms or tokens.

A string, however, consists of a lot of characters. In order to compare strings, you, in the worst case, have to look at every character of the strings. Which can turn in to N ^ N comparisons in  worst case.

In fact, when you compare strings, you're most likely using an integer comparison for each character in the string. You can probably see how this quickly can turn into a lot of comparisons as compared to comparing two integers or floating point numbers.

Example: If you want to compare 1073741822 with 1073741823.

String comparison: You have to compare each of the digits one by one. This is 10 comparisons, since the integers only differ by the last digit.
Integer comparison: You can do this in one comparison, saving 9 comparisons as compared to the String comparison.

Hope this helps and Have Fun!

Thanks,
Sumod

**Comment by nimisha84** [comment]
The .Net SDK has defined the realmId as string and therefore it is advisable to use String format.

**Comment by varikhehra** [comment]
Thanks Sumod! Everything is working fine finally after making following changes.
1. Changed realmid to long in app code
2. Changed realmid to bigint in DB
3. Disable DB migrations.

**Comment by smathilakath** [comment]
Awesome.

**Comment by piyushseth** [comment]
@varikhehra
1. Changed realmid to long in app code
2. Changed realmid to bigint in DB
**3. Disable DB migrations.**

What did you changed to disable DB migrations, which files did you changed ?

Thanks
Piyush

**Comment by pvogel1967** [comment]
PLEASE, PLEASE change this to strings, NOT longs/bigints.  In a future state these will NOT be numeric.

**Comment by varikhehra** [comment]
@piyushseth 
![change1](https://cloud.githubusercontent.com/assets/6885749/16166659/24e34daa-34bb-11e6-8de0-b7e04eae887a.jpg)

![change2](https://cloud.githubusercontent.com/assets/6885749/16166661/29fa2ffc-34bb-11e6-961b-e384e508b2ba.jpg)

**Comment by smathilakath** [comment]
Super cool. I assume in the current context or scope realmid are numeric. Keeping the scope as numeric it is important to understand the merits vs demerits of long vs string. The computation capacity long offer over string with less memory foot print and overheads example O(1) comparison. Now, Let us assume we move the scope little ahead of time where **realmid** are **alphanumeric**. I still won't recommend string because of its overhead and memory foot print. I would recommend **char[]** because string is immutable in nature. The compiler certainly has to do branch and bound optimisation technique. String generates a string pool data structure to manage its allocation in heap.The following simple exercise can validate the understanding. Generate 3 consecutive memory dumps of worker process using **debugdiag**. Load the dumps in to **WinDbg**. Execute the following commands **execute !heap -s** . It will give you the growing heap. Execute **“!heap -stat –h 00330000”** which will give you heap statistics. You can get the address blocks using **!heap -flt s 1f64**. You can use  **!heap -p -a UsrPtr** to display call stack. You can compare the memory foot print of **char[] vs String**. if you are storing password or want to keep realm more secure certainly not string because we can view your **realmid** in the dump.  Beware of Substring() method of String class. if not used wisely it will blow your RAM.I would recommend **string** if you are at ease and care less about performance. If you really want to squeeze the best of your RAM **char[]**.String internally use **char[]** but why do you need the overheads for your algorithm if you know what are you are doing with it and has a fixed size.Objects of type String are immutable, i.e., there are no methods defined that allow you to change (overwrite) or zero out the contents of a String after usage. This feature makes String objects unsuitable for storing security sensitive information such as user passwords. You should always collect and store security sensitive information in a  char array instead. Your RealmId are easily visible as it spits out Plain Text. Nothing is fool proof but it is your honest efforts to bring down compromise easily. It is in your best interest that **RealmId** should not be compromised easily.

Good luck and Hope this Helps!
Let your RAM Rest In Peace.

Ref:
https://www.microsoft.com/en-in/download/details.aspx?id=26798
http://www.windbg.org/
http://www.dumpanalysis.org/CDAPoster.html

**About me** : I am an ex Microsoft employee. I was part of the Microsoft IIS and ASP.NET team. You can refer the blogs of me and my colleagues if it helps.

Ref:
https://blogs.msdn.microsoft.com/kaushal/2013/08/02/ssl-handshake-and-https-bindings-on-iis/
https://blogs.msdn.microsoft.com/chiranth/2013/09/20/all-about-kerberos-the-three-headed-dog-with-respect-to-iis-and-sql/

**Comment by piyushseth** [comment]
Thanks @varikhehra , this was helpful
